services:
  nginx:
    image: nginx
    container_name: nginx_main
    ports:
      - "80:80"
    volumes:
    - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./configs/nginx/conf.d:/etc/nginx/conf.d
    - ./configs/nginx/sites-enabled/:/etc/nginx/sites-enabled/
    - ./nginx_logs:/var/log/nginx
      #medium.100projectx.com
    - /home/srijan/CS/medium/frontend/dist:/app/medium

    networks:
      - website-network

# current.100projectx.com
  current:
    
    restart: always
    image: node:latest
    container_name: current
    networks:
      - website-network
    volumes:
      - /home/srijan/CS/nextK:/app:rw
    command: /bin/bash -c "cd /app && npm run build && npm run start"

  location:
    
    image: node:latest
    container_name: live_location
    volumes:
     - /home/srijan/CS/location/:/app
    working_dir: /app
    entrypoint: node /app/backend/app.js
    command: echo "starting app" && node backend/app.js
    networks:
      - website-network
    



networks:
  website-network:

