services:
  nginx:
    image: nginx
    container_name: nginx_main
    ports:
      - "80:80"
    volumes:
    - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./configs/nginx/conf.d:/etc/nginx/conf.d

    networks:
      - website-network

  current:
    tty: true
    image: node:latest
    container_name: current
    networks:
      - website-network
    volumes:
      - /home/srijan/CS/nextK:/app:rw
    command: /bin/bash -c "cd /app && npm run build && npm run start"


      
        
    



networks:
  website-network:
